### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by pafels** [suma12/amr#2]
I am extracting raw stream from a pcap and in most of the cases everything is ok and I get an amr file. The command I am using is:
python2.7 amr.py q_uniq.raw

Most of the streams are rtp type 102. But some of them are 96. For those with 96 I get the following error:

python2.7 amr.py q_uniq.raw
Traceback (most recent call last):
  File "amr.py", line 263, in <module>
    a.processFile(args.raw)
  File "amr.py", line 159, in processFile
    self.process(f.read())
  File "amr.py", line 148, in process
    mode >= self.invalidMode[1]
AssertionError

Any idea? I am not sure it is related to rtp type but this is the only difference I found.

**Comment by MyLoveES** [comment]
maybe invalid fram, refer to https://datatracker.ietf.org/doc/html/rfc4867#page-18
